// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/client.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateClientRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname              string   `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	Lastname             string   `protobuf:"bytes,4,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Age                  uint32   `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Weight               uint32   `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Height               uint32   `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClientRequest) Reset()         { *m = CreateClientRequest{} }
func (m *CreateClientRequest) String() string { return proto.CompactTextString(m) }
func (*CreateClientRequest) ProtoMessage()    {}
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a0e6f5862e4b85, []int{0}
}

func (m *CreateClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientRequest.Unmarshal(m, b)
}
func (m *CreateClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientRequest.Marshal(b, m, deterministic)
}
func (m *CreateClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientRequest.Merge(m, src)
}
func (m *CreateClientRequest) XXX_Size() int {
	return xxx_messageInfo_CreateClientRequest.Size(m)
}
func (m *CreateClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientRequest proto.InternalMessageInfo

func (m *CreateClientRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateClientRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateClientRequest) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *CreateClientRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *CreateClientRequest) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *CreateClientRequest) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *CreateClientRequest) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type CreateClientResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClientResponse) Reset()         { *m = CreateClientResponse{} }
func (m *CreateClientResponse) String() string { return proto.CompactTextString(m) }
func (*CreateClientResponse) ProtoMessage()    {}
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a0e6f5862e4b85, []int{1}
}

func (m *CreateClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientResponse.Unmarshal(m, b)
}
func (m *CreateClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientResponse.Marshal(b, m, deterministic)
}
func (m *CreateClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientResponse.Merge(m, src)
}
func (m *CreateClientResponse) XXX_Size() int {
	return xxx_messageInfo_CreateClientResponse.Size(m)
}
func (m *CreateClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientResponse proto.InternalMessageInfo

func (m *CreateClientResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadClientRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadClientRequest) Reset()         { *m = ReadClientRequest{} }
func (m *ReadClientRequest) String() string { return proto.CompactTextString(m) }
func (*ReadClientRequest) ProtoMessage()    {}
func (*ReadClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a0e6f5862e4b85, []int{2}
}

func (m *ReadClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadClientRequest.Unmarshal(m, b)
}
func (m *ReadClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadClientRequest.Marshal(b, m, deterministic)
}
func (m *ReadClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadClientRequest.Merge(m, src)
}
func (m *ReadClientRequest) XXX_Size() int {
	return xxx_messageInfo_ReadClientRequest.Size(m)
}
func (m *ReadClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadClientRequest proto.InternalMessageInfo

func (m *ReadClientRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadClientResponse struct {
	Client               *CreateClientRequest `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReadClientResponse) Reset()         { *m = ReadClientResponse{} }
func (m *ReadClientResponse) String() string { return proto.CompactTextString(m) }
func (*ReadClientResponse) ProtoMessage()    {}
func (*ReadClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a0e6f5862e4b85, []int{3}
}

func (m *ReadClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadClientResponse.Unmarshal(m, b)
}
func (m *ReadClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadClientResponse.Marshal(b, m, deterministic)
}
func (m *ReadClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadClientResponse.Merge(m, src)
}
func (m *ReadClientResponse) XXX_Size() int {
	return xxx_messageInfo_ReadClientResponse.Size(m)
}
func (m *ReadClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadClientResponse proto.InternalMessageInfo

func (m *ReadClientResponse) GetClient() *CreateClientRequest {
	if m != nil {
		return m.Client
	}
	return nil
}

type UpdateClientRequest struct {
	Client               *CreateClientRequest `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateClientRequest) Reset()         { *m = UpdateClientRequest{} }
func (m *UpdateClientRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateClientRequest) ProtoMessage()    {}
func (*UpdateClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a0e6f5862e4b85, []int{4}
}

func (m *UpdateClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateClientRequest.Unmarshal(m, b)
}
func (m *UpdateClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateClientRequest.Marshal(b, m, deterministic)
}
func (m *UpdateClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateClientRequest.Merge(m, src)
}
func (m *UpdateClientRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateClientRequest.Size(m)
}
func (m *UpdateClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateClientRequest proto.InternalMessageInfo

func (m *UpdateClientRequest) GetClient() *CreateClientRequest {
	if m != nil {
		return m.Client
	}
	return nil
}

type UpdateClientResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateClientResponse) Reset()         { *m = UpdateClientResponse{} }
func (m *UpdateClientResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateClientResponse) ProtoMessage()    {}
func (*UpdateClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a0e6f5862e4b85, []int{5}
}

func (m *UpdateClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateClientResponse.Unmarshal(m, b)
}
func (m *UpdateClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateClientResponse.Marshal(b, m, deterministic)
}
func (m *UpdateClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateClientResponse.Merge(m, src)
}
func (m *UpdateClientResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateClientResponse.Size(m)
}
func (m *UpdateClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateClientResponse proto.InternalMessageInfo

func (m *UpdateClientResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteClientRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteClientRequest) Reset()         { *m = DeleteClientRequest{} }
func (m *DeleteClientRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteClientRequest) ProtoMessage()    {}
func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a0e6f5862e4b85, []int{6}
}

func (m *DeleteClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClientRequest.Unmarshal(m, b)
}
func (m *DeleteClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClientRequest.Marshal(b, m, deterministic)
}
func (m *DeleteClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClientRequest.Merge(m, src)
}
func (m *DeleteClientRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteClientRequest.Size(m)
}
func (m *DeleteClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClientRequest proto.InternalMessageInfo

func (m *DeleteClientRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteClientResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteClientResponse) Reset()         { *m = DeleteClientResponse{} }
func (m *DeleteClientResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteClientResponse) ProtoMessage()    {}
func (*DeleteClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a0e6f5862e4b85, []int{7}
}

func (m *DeleteClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClientResponse.Unmarshal(m, b)
}
func (m *DeleteClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClientResponse.Marshal(b, m, deterministic)
}
func (m *DeleteClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClientResponse.Merge(m, src)
}
func (m *DeleteClientResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteClientResponse.Size(m)
}
func (m *DeleteClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClientResponse proto.InternalMessageInfo

func (m *DeleteClientResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateClientRequest)(nil), "simple_crud_example.CreateClientRequest")
	proto.RegisterType((*CreateClientResponse)(nil), "simple_crud_example.CreateClientResponse")
	proto.RegisterType((*ReadClientRequest)(nil), "simple_crud_example.ReadClientRequest")
	proto.RegisterType((*ReadClientResponse)(nil), "simple_crud_example.ReadClientResponse")
	proto.RegisterType((*UpdateClientRequest)(nil), "simple_crud_example.UpdateClientRequest")
	proto.RegisterType((*UpdateClientResponse)(nil), "simple_crud_example.UpdateClientResponse")
	proto.RegisterType((*DeleteClientRequest)(nil), "simple_crud_example.DeleteClientRequest")
	proto.RegisterType((*DeleteClientResponse)(nil), "simple_crud_example.DeleteClientResponse")
}

func init() {
	proto.RegisterFile("proto/client.proto", fileDescriptor_f1a0e6f5862e4b85)
}

var fileDescriptor_f1a0e6f5862e4b85 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xd1, 0x4a, 0x02, 0x41,
	0x14, 0x65, 0xd5, 0x46, 0xbb, 0x61, 0xd4, 0x5d, 0x89, 0xc5, 0x27, 0xd9, 0xc8, 0xec, 0x45, 0xc1,
	0x7e, 0x20, 0x32, 0xe8, 0x7d, 0xa1, 0x84, 0x40, 0x64, 0x73, 0x2f, 0xba, 0xb0, 0xea, 0x36, 0x33,
	0x52, 0x3f, 0xd0, 0x07, 0xf5, 0x87, 0xb1, 0x77, 0xb6, 0x68, 0x73, 0x36, 0x85, 0x9e, 0x76, 0xee,
	0x99, 0x33, 0x87, 0x73, 0xcf, 0x61, 0x01, 0x53, 0xb9, 0xd6, 0xeb, 0xc1, 0x2c, 0x89, 0x69, 0xa5,
	0xfb, 0x3c, 0xa0, 0xab, 0xe2, 0x65, 0x9a, 0xd0, 0x74, 0x26, 0x37, 0xd1, 0x94, 0xde, 0xc2, 0x6c,
	0xf0, 0x3f, 0x1c, 0x70, 0x47, 0x92, 0x42, 0x4d, 0x23, 0xe6, 0x06, 0xf4, 0xb2, 0x21, 0xa5, 0xf1,
	0x18, 0x2a, 0x71, 0xe4, 0x39, 0x1d, 0xa7, 0x77, 0x18, 0x54, 0xe2, 0x08, 0x11, 0x6a, 0xab, 0x70,
	0x49, 0x5e, 0x85, 0x11, 0x3e, 0xa3, 0x07, 0x75, 0xb5, 0x91, 0x0c, 0x57, 0x19, 0xfe, 0x1a, 0xb1,
	0x0d, 0x8d, 0x24, 0x54, 0x9a, 0xaf, 0x6a, 0x7c, 0xf5, 0x3d, 0xe3, 0x09, 0x54, 0xc3, 0x39, 0x79,
	0x07, 0x1d, 0xa7, 0xd7, 0x0c, 0xb2, 0x23, 0x9e, 0x81, 0x78, 0xa5, 0x78, 0xbe, 0xd0, 0x9e, 0x60,
	0x30, 0x9f, 0x32, 0x7c, 0x61, 0xf0, 0xba, 0xc1, 0xcd, 0xe4, 0x77, 0xa1, 0x55, 0xb4, 0xac, 0xd2,
	0xf5, 0x4a, 0xd1, 0x6f, 0xcf, 0xfe, 0x39, 0x9c, 0x06, 0x14, 0x46, 0x7f, 0x2e, 0xe6, 0x3f, 0x02,
	0xfe, 0x24, 0xe5, 0x52, 0x37, 0x20, 0x4c, 0x76, 0xcc, 0x3c, 0x1a, 0xf6, 0xfa, 0x96, 0xf0, 0xfa,
	0x96, 0xe0, 0x82, 0xfc, 0x9d, 0x3f, 0x06, 0xf7, 0x21, 0x8d, 0xb6, 0x72, 0xfd, 0xbf, 0x70, 0x17,
	0x5a, 0x45, 0xe1, 0x92, 0xed, 0x2f, 0xc0, 0xbd, 0xa3, 0x84, 0x76, 0x14, 0x9b, 0xc9, 0x15, 0x69,
	0x76, 0xb9, 0xe1, 0x7b, 0x15, 0x9a, 0x86, 0x72, 0x2f, 0x89, 0x34, 0x49, 0x9c, 0x80, 0x30, 0x3e,
	0x71, 0xef, 0x25, 0xda, 0x57, 0x7b, 0x30, 0x73, 0x03, 0x63, 0xa8, 0x65, 0xc5, 0x60, 0xd7, 0xfa,
	0x64, 0xab, 0xd8, 0xf6, 0xe5, 0x4e, 0x5e, 0x2e, 0x3c, 0x01, 0x61, 0x02, 0x2c, 0xf1, 0x6d, 0xa9,
	0xad, 0xc4, 0xb7, 0xb5, 0x87, 0x09, 0x08, 0x13, 0x68, 0x89, 0xbc, 0xa5, 0x94, 0x12, 0x79, 0x5b,
	0x2f, 0xb7, 0x8d, 0x27, 0x31, 0xe0, 0xff, 0xf9, 0x59, 0xf0, 0xe7, 0xfa, 0x33, 0x00, 0x00, 0xff,
	0xff, 0x2f, 0x10, 0x8e, 0xc4, 0xec, 0x03, 0x00, 0x00,
}
